In [17]:
!nvidia-smi

Fri Jul 12 21:29:54 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   37C    P8             14W /  200W |     769MiB /  12282MiB |     17%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
 
print(f"Is CUDA supported by this system? {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")
 
# Storing ID of current CUDA device
cuda_id = torch.cuda.current_device()
print(f"ID of current CUDA device: {torch.cuda.current_device()}")
       
print(f"Name of current CUDA device: {torch.cuda.get_device_name(cuda_id)}")

Is CUDA supported by this system? True
CUDA version: 11.8
ID of current CUDA device: 0
Name of current CUDA device: NVIDIA GeForce RTX 4070


Introduction to Tensors

Creating Tensors


In [3]:
#scalar
scalar = torch.tensor(10)
print(scalar)

tensor(10)


In [4]:
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

10

Vector - Has the magnitude and direction it is represented in array or list format

In [15]:
vector=torch.tensor([7,7])
print(vector)
print('The dimension - ',vector.ndim)
print(vector.shape)

tensor([7, 7])
The dimension  1
torch.Size([2])


MATRIX

In [20]:
matrix = torch.tensor([[7,7],
                       [9,10]])
print(matrix)
print('The dimension - ',matrix.ndim)
print(matrix.shape)
print('Getting the values based on index i - ',matrix[1])
print('Getting the values based on index i & j - ',matrix[1][1])

tensor([[ 7,  7],
        [ 9, 10]])
The dimension -  2
torch.Size([2, 2])
Getting the values based on index i -  tensor([ 9, 10])
Getting the values based on index i & j -  tensor(10)


Tensor

In [27]:
TENSOR = torch.tensor([[[1,2,3],
                        [5,6,7],
                        [10,11,12]
                         ]])

print(TENSOR)
print('The dimension - ',TENSOR.ndim)
print(TENSOR.shape)
print('Getting the values based on index i - ',TENSOR[0]) # It means it has 1 3 * 3 matrix inside the tensor
print('Getting the values based on index i - ',TENSOR[0][1][2])

tensor([[[ 1,  2,  3],
         [ 5,  6,  7],
         [10, 11, 12]]])
The dimension -  3
torch.Size([1, 3, 3])
Getting the values based on index i -  tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [10, 11, 12]])
Getting the values based on index i -  tensor(7)
